### ISSUE TITLE
How to use this configurator

### ISSUE THREAD

**Issue by Qussayyon** [mlocati/php-cs-fixer-configurator#1]
Hi @mlocati,

I would like to ask you how to use this configurator?

I didn't figure it out!

**Comment by mlocati** [comment]
There are two modes: the default mode is used to view all the fixers, including the configuration options and examples.
There's also the "configurator" mode that can be used to select and configure the fixers you want. Hit the question mark icon to get more details.

**Comment by Qussayyon** [comment]
Thanks @mlocati ,

I'm sorry but how to install this 'configurator' :angel:

**Comment by mlocati** [comment]
https://mlocati.github.io/php-cs-fixer-configurator is "just" a tool to visually create the content of the `.phpcs` (or `.phpcs.dist) files, that will be used by [php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer).

**Comment by Qussayyon** [comment]
Thanks @mlocati,
So I just need to go to:
https://mlocati.github.io/php-cs-fixer-configurator
then from there generate `.phpcs`.
right?

Thanks again.

**Comment by mlocati** [comment]
Yes
