### ISSUE TITLE
Discover "new" fixers more easily

### ISSUE THREAD

**Issue by ro0NL** [mlocati/php-cs-fixer-configurator#10]
Hi,

This tool is awesome.

When actively updating to the latest available fixers, it would be super helpful to be able to filter by version in a way you'd only see the fixers that are "new" in version X.

Much like a diff between e.g. 2.14 and 2.15

Thoughts?

**Comment by ro0NL** [comment]
Right i use https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases, copy paste the camel-cased new fixer names, convert to snake case, and search in the configurator. Rinse and repeat.

It's quite tedious :(

**Comment by mlocati** [comment]
I just updated the code: you should now have a new "Compare versions" item in the versions dropdown menu.
At the moment it will list added/removed fixers and fixer sets, but I'm planning to add a way to display the changes in fixers (eg new options, changed options, deprecation, risky, ...) and fixer sets (eg new fixers added, fixers removed, changes in settings, ...).

**Comment by ro0NL** [comment]
Perfect :ok_hand: thank you very much.

**Comment by mlocati** [comment]
> I'm planning to add a way to display the changes in fixers (eg new options, changed options, deprecation, risky, ...) and fixer sets (eg new fixers added, fixers removed, changes in settings, ...).

Done.

**Comment by ro0NL** [comment]
:clap:
