### ISSUE TITLE
Little bugs

### ISSUE THREAD

**Issue by WinterSilence** [mlocati/php-cs-fixer-configurator#14]
At first, thank you for that nice service!

Bugs:
1. Wrong examples:
~~~
    [
        'break',
        'continue',
        'declare',
        'return',
        'throw',
        'try',
    ]
~~~
this is NOT JSON array:
> Strings are delimited with double-quotation marks

`,` after last element, maybe fix here: https://github.com/mlocati/php-cs-fixer-configurator/blob/badb0a29a85fc3c27c8f0d6acac5b516502729f9/php/JsonEncoder.php#L120

2.  Switch between `Define custom value` and `Use default value` reset my value in `textarea`.

**Comment by mlocati** [comment]
Where do you see this code?
Please remark that somewhere I display the values in PHP format, bot in JSON format (and this seems PHP format).

**Comment by WinterSilence** [comment]
![изображение](https://user-images.githubusercontent.com/3521094/76159965-e701bb00-6136-11ea-9297-668f406dce07.png)

**Comment by mlocati** [comment]
Yep, those values are in PHP format

**Comment by WinterSilence** [comment]
@mlocati my mistake, but in config tab:
> Please specify a value of type array in JSON format:

**Comment by mlocati** [comment]
Yep, data is displayed in PHP format (because it's the format that PHP users are most familiar with), but when you configure the fixes you have to specify the data in JSON format (because parsing JSON is much more easy via JavaScript).
I

**Comment by WinterSilence** [comment]
@mlocati 
> but when you configure the fixes you have to specify the data in JSON format

look `token_get_all()`,  may be use combo format?
~~~
// $array = '['a', 'b',]'
$array = strtr($array, ["'" => '"', ',]' => ']']);
~~~

**Comment by WinterSilence** [comment]
@mlocati  also can u add ruleset `@psr12` https://www.tomasvotruba.com/blog/2018/04/09/try-psr-12-on-your-code-today/ https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4502 ? it's not official and maybe not complete list, but i use it half year and dont find problems + CodeSniffer use same rules - i check it.

**Comment by mlocati** [comment]
The whole app is client-side only, so it can only use Javascript, not PHP

**Comment by mlocati** [comment]
The fixer sets are only extracted from Php-Cs-Fixer code, there's not support for custom sets. But I guess that in the near future Php-Cs-Fixer will provide a PSR-12 fixer set

**Comment by WinterSilence** [comment]
@mlocati  
> The whole app is client-side only, so it can only use Javascript, not PHP

I'm talk about normalize user inputs, not exported configuration

**Comment by mlocati** [comment]
> May be use combo format?
>
> // $array = '['a', 'b',]'
> $array = strtr($array, ["'" => '"', ',]' => ']']);

Where?

**Comment by WinterSilence** [comment]
@mlocati I'm lose 'Something like this:'. Sorry, I'm dont know typescript and cant help to you

**Comment by WinterSilence** [comment]
@mlocati update: dirty fix, for example `arr = arr.replace(/'/, '"').replace(/,\]/, ']');`

**Comment by WinterSilence** [comment]
@mlocati 
> But I guess that in the near future Php-Cs-Fixer will provide a PSR-12 fixer set

as you can see (second link) it's not near future and it's jam long time ago

**Comment by mlocati** [comment]
I'm going to close this because:
1. I'm not going to create my own fixer set for PSR-12. PHP-CS-Fixer Configurator is "just" a wrapper around php-cs-fixer data, it's not meant to do anything else (I don't have time to maintain custom fixer set rules)
2. the examples display values in PHP format, since this configurator is meant to help PHP developers in writing php-cs-fixer rules (which should be written in PHP)
3. when you use PHP-CS-Fixer Configurator to create the php-cs-fixer rules, and you need to specify the options of the rules, PHP-CS-Fixer Configurator accepts JSON data (because it's written TypeScript, where there's no easy way to parse PHP code)
