### ISSUE TITLE
Cant delete excluded rules

### ISSUE THREAD

**Issue by WinterSilence** [mlocati/php-cs-fixer-configurator#15]
![изображение](https://user-images.githubusercontent.com/3521094/76162835-2b4e8480-6152-11ea-9309-8911e4849610.png)
in console: `TypeError: "e is null"`, prepend `event || `  to `event.preventDefault()`

**Comment by WinterSilence** [comment]
also,  `@PSR2` contained `@PSR1`,   `@PHP70Migration` contained `@PHP56Migration` and etc. current filter ignore it.

**Comment by mlocati** [comment]
What about submitting a pull request to fix the issue?

**Comment by WinterSilence** [comment]
@mlocati sorry, don't have time to code review
