### ISSUE TITLE
Losing required properties of rules

### ISSUE THREAD

**Issue by WinterSilence** [mlocati/php-cs-fixer-configurator#16]
As example: rule `header_comment`  added as: `'header_comment' => ['comment_type'=>'PHPDoc'],` and dont contain required property `header`.

**Comment by mlocati** [comment]
Are they lost?
Using the example of the `header` property of the `header_comment` fixer, do you mean that you configure `header` with https://mlocati.github.io/php-cs-fixer-configurator and when you export the configuration you don't have the `header` property?

**Comment by WinterSilence** [comment]
@mlocati exported the configuration don't have the header attribute

**Comment by WinterSilence** [comment]
@mlocati by default this attribute not existed in array, i'm think need add HTML attr required to inputs like this

**Comment by WinterSilence** [comment]
@mlocati if you add `header_comment` without  confuguration:
~~~
<?php
return PhpCsFixer\Config::create()
    ->setRules([
        'header_comment' => true,
    ])
~~~

**Comment by mlocati** [comment]
This is working for me:

![header-option-value](https://user-images.githubusercontent.com/928116/85308322-61b9d080-b4b1-11ea-9176-6a109da50592.gif)
