### ISSUE TITLE
Permalink/URL to Specific Fixer Modal

### ISSUE THREAD

**Issue by bmeynell** [mlocati/php-cs-fixer-configurator#2]
Currently there is no way to link to a specific Fixer and open its associated modal. Such functionality would be incredibly handy as it would enable direct linking to individual Fixers.

For example, a URL such as https://mlocati.github.io/php-cs-fixer-configurator/#blank_line_after_opening_tag would automatically open the `blank_line_after_opening_tag` modal:

<img width="1049" alt="php-cs-fixer configurator" src="https://user-images.githubusercontent.com/1051554/41562637-3d12eb38-731b-11e8-9fa5-a054a9a5fec1.png">

**Comment by mlocati** [comment]
Done: the will be like this: https://mlocati.github.io/php-cs-fixer-configurator/#fixer:blank_line_after_opening_tag (or https://mlocati.github.io/php-cs-fixer-configurator/#fixer:blank_line_after_opening_tag|configurator if you want also to switch to the "configuration" mode)
