### ISSUE TITLE
Support for Symfony ContainerConfigurator

### ISSUE THREAD

**Issue by ckrack** [mlocati/php-cs-fixer-configurator#24]
Hi, thanks for the great tool!
Really helps to get a better overview and understanding of all the fixers.

I've moved to [symplify/easy-coding-standard](https://github.com/symplify/easy-coding-standard) as a tool, which internally uses php-cs-fixer and php_codesniffer.
The configuration is done with Symfony's new ContainerConfigurator.

Sadly, I can't reimport this into the configurator tool and it's not easy to compare/diff the fixers used.
This is an example taken from the ecs documentation:
```php
<?php
// ecs.php

declare(strict_types=1);

use PhpCsFixer\Fixer\ArrayNotation\ArraySyntaxFixer;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
use Symplify\EasyCodingStandard\Configuration\Option;

return static function (ContainerConfigurator $containerConfigurator): void {
    $services = $containerConfigurator->services();
    $services->set(ArraySyntaxFixer::class);

    $parameters = $containerConfigurator->parameters();
    $parameters->set(Option::ONLY, [
        ArraySyntaxFixer::class => [
            __DIR__ . '/src/NewCode'
        ]
    ]);
};
```

It would be great to have an importer/exporter for this.
I'm expecting it to be used more often, as Symfony is moving to this kind of configuration.

**Comment by mlocati** [comment]
Well, parsing and generating this syntax is a nightmare...

**Comment by ckrack** [comment]
I've already done the exporter, will try my luck on an importer later and hopefully be able to open a PR.
