### ISSUE TITLE
Ability to hide unused deprecated rules

### ISSUE THREAD

**Issue by weshooper** [mlocati/php-cs-fixer-configurator#29]
Love this tool, thank you!

An option to hide unused deprecated rules would help by reducing some noise in the list. We typically avoid using deprecated rules, so including them in the list offers no benefit. However, if we're still using a deprecated rule, listing it is helpful as a reminder to migrate.

**Comment by mlocati** [comment]
Done!

(and thanks!!!)

**Comment by weshooper** [comment]
@mlocati wow, fantastic - thanks!

**Comment by mlocati** [comment]
![immagine](https://user-images.githubusercontent.com/928116/96261458-c64cee00-0fc0-11eb-921f-cc104b3e38e8.png)
