### ISSUE TITLE
Meaning of the 'red rules'

### ISSUE THREAD

**Issue by ltdeta** [mlocati/php-cs-fixer-configurator#32]
The help say  "Fixers included in selected presets but explicitly excluded"

Where is it decided that this rule is not used, why is the rule excluded?

![grafik](https://user-images.githubusercontent.com/1563652/107484767-2e809a80-6b83-11eb-907b-e60186197164.png)

PS: Very good work, that facilitates the configuration extremely! :thumbsup:

**Comment by mlocati** [comment]
I'm not sure I understand your question...

When you select to use a preset (`@PHP74Migration` in your example), you'll see the included rules with light green.
If you want to exclude a specific rule that's included in a preset, you can simply click that rule:

![pcf-excluded-rules](https://user-images.githubusercontent.com/928116/107488039-20cd1400-6b87-11eb-92c3-d0fbbf1841bf.gif)

With to rules excluded from the preset, you'll have this `.php-cs.php` file:

```php
<?php
return PhpCsFixer\Config::create()
    ->setRules([
        '@PHP74Migration' => true,
    ])
    // ...
;
```

if you manually exclude a specific rule, you'll have this:

```php
<?php
return PhpCsFixer\Config::create()
    ->setRules([
        '@PHP74Migration' => true,
        'array_syntax' => false,
    ])
    // ...
;
```

Does that answer your question?

**Comment by ltdeta** [comment]
I do not understand why `array_syntax` is automatically explicitly excluded when i use `@PHP74Migration` ?

**Comment by mlocati** [comment]
Maybe you clicked on it with the mouse?

**Comment by ltdeta** [comment]
Sorry, now it works, probably you were right :flushed:
