### ISSUE TITLE
Display configuration used by sets when not using the default

### ISSUE THREAD

**Issue by stof** [mlocati/php-cs-fixer-configurator#4]
Sets can enable fixers with a custom config rather than relying on the default one. The `@Symfony:risky` set does it for some fixers for instance. But the UI does not display that (while `php-cs-fixer describe` does)

**Comment by mlocati** [comment]
If you click on the fixer sets you should see the fixer configurations:

![fixersets-options](https://user-images.githubusercontent.com/928116/44099555-2f63a76c-9fe3-11e8-946e-ee94e60ab763.gif)

**Comment by stof** [comment]
but if you click on the card itself top open the details about the fixer, while having a set applied as filter, I would expect to see the info too.

**Comment by stof** [comment]
thus, the question mark cursor on the set label did not made me think it was actually clickable, and so I missed this modal

**Comment by mlocati** [comment]
Done :wink:
