### ISSUE TITLE
Being able to show "not in"

### ISSUE THREAD

**Issue by gemal** [mlocati/php-cs-fixer-configurator#40]
We are using `@PSR12` set and I looking into adding some more fixes

So I would like to see `@PhpCsFixer` but ONLY those fixes that are not already in `@PSR12`

Is there a way to do this in the interface?

**Comment by mlocati** [comment]
There's no way to hide fixers belinging to a set. And I'm sorry but I'm not going to implement such a feature (the UI is already too much complicated for me).

Here's what I'd do to pick and eventually configure fixers that don't belong to `@PSR12`:

1. enter the configurator mode
2. choose the `@PSR12` set
3. you'll see the fixers belonging to in with a light green background
   ![immagine](https://user-images.githubusercontent.com/928116/209293431-e66a570a-ddb2-49cd-b2f0-7185da294cc9.png)
4. you can configure all the other fixers
6. you can finally unselect the `@PSR12` set
