### ISSUE TITLE
Impossible to set option custom value in `blank_lines_before_namespace`

### ISSUE THREAD

**Issue by GRIDARK** [mlocati/php-cs-fixer-configurator#41]
Hello. It`s an excellent tool. Tnx.

I`m using Firefox 118.0b6 (developer edition) and found a nasty bug.

### Subject

Impossible to set option custom value in `blank_lines_before_namespace`.

I want set custom value for `blank_lines_before_namespace`, but get error message `Error: The type of the option max_line_breaks of the fixer blank_lines_before_namespace is not an accepted one`. 

### Reproduce

1. Go to [configurator](https://mlocati.github.io/php-cs-fixer-configurator/)
2. Search `blank_lines_before_namespace` and select it
3. Try config this statement and define custom value any option (ex. max_line_breaks = 1)
4. Apply changes
5. Take error message

### Investigation

I did a little research and found this situation.

https://github.com/mlocati/php-cs-fixer-configurator/blob/3b7a04d33e06ff26a44659f5ecfd8f4f708bc4f8/web/Fixer.ts#L244-L312

In string `#294` you use long definition `integer`, but in config use short definition

https://github.com/mlocati/php-cs-fixer-configurator/blob/3b7a04d33e06ff26a44659f5ecfd8f4f708bc4f8/docs/data/3.25.1.json#L449-L467

![изображение](https://github.com/mlocati/php-cs-fixer-configurator/assets/2919313/7c2859a1-f331-4159-ab74-fb643f7fcacd)

**Comment by mlocati** [comment]
Fixed by #42
