### ISSUE TITLE
Commit `composer.lock`

### ISSUE THREAD

**Issue by Shikachuu** [mlocati/php-cs-fixer-configurator#45]
Hello,

First of all thanks for the project, it makes configuration way easier.

Reason of this issue: https://getcomposer.org/doc/01-basic-usage.md#installing-from-composer-lock

## Current Behaviour

If you freshly clone the project and run `composer install`, it has a chance to install slightly different depenceies than the PR author have.

This can cause hard-to-reproduce buggs since all the PHP dependencies only have the major versions pinned. `"^2 || ^3"`

This problem can occure even in CI since the `composer.lock` file is on `.gitignore`.

## Possible Solution

Commit the `composer.lock` file for consistent depenceny behaviour.

**Comment by mlocati** [comment]
The dependency on php-cs-fixer is (and must be) unlocked, since the role of this project is to parse multiple php-cs-fixer versions.
Locking to a specific version is absolutely useless.

**Comment by mlocati** [comment]
See #52
