### ISSUE TITLE
Add php-cs-fixer for the PHP part of the project

### ISSUE THREAD

**Issue by Shikachuu** [mlocati/php-cs-fixer-configurator#46]
Hello,

Most of the time it is good practice, to dog-food projects like this.

## Current Behaviour

No `php-cs-fixer` rules included.

## Possible Solution

Add `php-cs-fixer` rules to the PHP code and optionally introduce a a CI pipeline for PRs.

**Comment by mlocati** [comment]
> No `php-cs-fixer` rules included.

[They are](https://github.com/mlocati/php-cs-fixer-configurator/blob/main/.php_cs.dist) (even if rather old).
