### ISSUE TITLE
Bug indent select

### ISSUE THREAD

**Issue by koromerzhin** [mlocati/php-cs-fixer-configurator#6]
The only supported indents are 2 spaces, 4 spaces and tabs. This is reflected throughout other fixers as well.

[pull request php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4150)

**Comment by mlocati** [comment]
Fixed by 9eb0d38431e21b6fa2a856ae8ef2352a855be5ca
