### ISSUE TITLE
Rule `braces` is missing

### ISSUE THREAD

**Issue by ljubadr** [mlocati/php-cs-fixer-configurator#68]
Thanks for this great tool! I makes using `php-cs-fixer` much easier

In the config when I search for `braces` I don't see it in the results. Here is the [Rule Braces](https://cs.symfony.com/doc/rules/basic/braces.html) page

**Comment by mlocati** [comment]
It's there, but since it's deprecated you have to tell the tool to show deprecated rules

![Screenshot_20240620-234826_Firefox](https://github.com/mlocati/php-cs-fixer-configurator/assets/928116/d861555e-6659-4a54-b067-c4f8587fe018)

**Comment by ljubadr** [comment]
Oh, I completely missed the deprecated warning in the link that I posted. I was already using `braces` rule and I wanted to check possible config values

Sorry about that and thanks for the clarification
