### ISSUE TITLE
Modal bug

### ISSUE THREAD

**Issue by gusbemacbe** [mlocati/php-cs-fixer-configurator#7]
Ciao/Hello @mlocati !

:gb: When I close the modal box, I am forwarded to the page top. I have to scroll down every time that I close the modal box.
:it: Quando io chiudo il dialogo del modal, mi porta fino alla parte superiore della pagina. Devo scorrere verso il basso la pagina ogni volta che chiudo il dialogo del modal.

**Comment by mlocati** [comment]
Which modal box? Could you post a screenshot?

**Comment by gusbemacbe** [comment]
Ciao/hello,

Here is the gif/Ecco il gif:

![modal_bug](https://user-images.githubusercontent.com/2257024/56263457-599a2000-60b9-11e9-8d86-fc2268f6bbf5.gif)

**Comment by mlocati** [comment]
Fixed by https://github.com/mlocati/php-cs-fixer-configurator/commit/6511329d8256f5248797a6d870941e238c48250a
