### ISSUE TITLE
Validating the type of custom value of a fixer parameter

### ISSUE THREAD

**Issue by Disparity** [mlocati/php-cs-fixer-configurator#8]
Hi!

The configurator is a good product, but there is an error with types when setting the custom value of a parameter.

Associative php array cannot be represented as a json array, only as an object. But the validator strictly requires only an array.

Also, an error occurs if you load the configuration, and open the parameter value. It will be an object, but when you try to save it will show an error.

For example, you can check on the **binary_operator_spaces** fixer, set the **operators** parameter value **{"=": "align"}**

**Comment by mlocati** [comment]
Thanks for the report!

Fixed by 8201959f2f3390dafef9dbf7395340e1ed94ccb1 and 02e2a7a092d26e085b635502d88c8e28e0d498cf
